name: malika
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  google_sign_in: ^5.4.2
  equatable: ^2.0.5
  go_router: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/