// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHEYIJX1DsxPagC6ddhWGahKbC-nqGSOE',
    appId: '1:896502002106:web:8e72539d8597f68b1f2d83',
    messagingSenderId: '896502002106',
    projectId: 'mallika-b9a86',
    authDomain: 'mallika-b9a86.firebaseapp.com',
    storageBucket: 'mallika-b9a86.appspot.com',
    measurementId: 'G-BJGCEGPP2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwSuuKKsOssEOj-Atvk9MKv_vkWGmlxuo',
    appId: '1:896502002106:android:6553b28d3472fdf41f2d83',
    messagingSenderId: '896502002106',
    projectId: 'mallika-b9a86',
    storageBucket: 'mallika-b9a86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_aW6yWcp3RBTR6GQk8j3mS2MqLUuDcJ8',
    appId: '1:896502002106:ios:72bee0f02eb2f65e1f2d83',
    messagingSenderId: '896502002106',
    projectId: 'mallika-b9a86',
    storageBucket: 'mallika-b9a86.appspot.com',
    androidClientId: '896502002106-oclbje7gfnclvthp37t6d4c911f08jbh.apps.googleusercontent.com',
    iosClientId: '896502002106-o1u3cdede8f36ctn4l3sp908o0i33sgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.malika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_aW6yWcp3RBTR6GQk8j3mS2MqLUuDcJ8',
    appId: '1:896502002106:ios:72bee0f02eb2f65e1f2d83',
    messagingSenderId: '896502002106',
    projectId: 'mallika-b9a86',
    storageBucket: 'mallika-b9a86.appspot.com',
    androidClientId: '896502002106-oclbje7gfnclvthp37t6d4c911f08jbh.apps.googleusercontent.com',
    iosClientId: '896502002106-o1u3cdede8f36ctn4l3sp908o0i33sgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.malika',
  );
}
